/*
    Modulo 4 (parte 2) - Stored Procedures del esqueleto de plantillas.
*/

USE AelbryDb;
GO

CREATE OR ALTER PROCEDURE dbo.SP_PROJECT_TEMPLATE_ACTIVITY_GET_BY_TEMPLATE
    @P_PROJECT_TEMPLATE_ID INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ProjectTemplateActivityId AS PROJECT_TEMPLATE_ACTIVITY_ID, ProjectTemplateId AS PROJECT_TEMPLATE_ID,
           Name AS NAME, Description AS DESCRIPTION, EstimatedHours AS ESTIMATED_HOURS, Sequence AS SEQUENCE,
           CreatedBy AS CREATED_BY, CreatedDate AS CREATED_DATE
    FROM dbo.ProjectTemplateActivity
    WHERE ProjectTemplateId = @P_PROJECT_TEMPLATE_ID
    ORDER BY Sequence, ProjectTemplateActivityId;
END
GO

CREATE OR ALTER PROCEDURE dbo.SP_PROJECT_TEMPLATE_ACTIVITY_INSERT
    @P_PROJECT_TEMPLATE_ID INT,
    @P_NAME NVARCHAR(200),
    @P_DESCRIPTION NVARCHAR(500) = NULL,
    @P_ESTIMATED_HOURS DECIMAL(9,2),
    @P_SEQUENCE INT,
    @P_CREATED_BY INT,
    @P_NEW_PROJECT_TEMPLATE_ACTIVITY_ID INT OUTPUT,
    @OUT_RESULT NVARCHAR(400) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        INSERT INTO dbo.ProjectTemplateActivity (ProjectTemplateId, Name, Description, EstimatedHours, Sequence, CreatedBy)
        VALUES (@P_PROJECT_TEMPLATE_ID, @P_NAME, @P_DESCRIPTION, @P_ESTIMATED_HOURS, @P_SEQUENCE, @P_CREATED_BY);

        SET @P_NEW_PROJECT_TEMPLATE_ACTIVITY_ID = CAST(SCOPE_IDENTITY() AS INT);
        SET @OUT_RESULT = 'OK';
    END TRY
    BEGIN CATCH
        SET @OUT_RESULT = ERROR_MESSAGE();
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE dbo.SP_PROJECT_TEMPLATE_ACTIVITY_DELETE
    @P_PROJECT_TEMPLATE_ACTIVITY_ID INT,
    @OUT_RESULT NVARCHAR(400) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        DELETE FROM dbo.ProjectTemplateActivity WHERE ProjectTemplateActivityId = @P_PROJECT_TEMPLATE_ACTIVITY_ID;
        SET @OUT_RESULT = 'OK';
    END TRY
    BEGIN CATCH
        SET @OUT_RESULT = ERROR_MESSAGE();
    END CATCH
END
GO
