/*
    Modulo 9 - Stored Procedures de Auditoria.
*/

USE AelbryDb;
GO

CREATE OR ALTER PROCEDURE dbo.SP_AUDIT_LOG_INSERT
    @P_COMPANY_ID INT,
    @P_USER_ID INT,
    @P_USER_NAME NVARCHAR(200),
    @P_IP_ADDRESS NVARCHAR(64) = NULL,
    @P_MODULE NVARCHAR(50),
    @P_ACTION NVARCHAR(50),
    @P_ENTITY_ID INT = NULL,
    @P_DATA_BEFORE NVARCHAR(MAX) = NULL,
    @P_DATA_AFTER NVARCHAR(MAX) = NULL,
    @OUT_RESULT NVARCHAR(400) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        INSERT INTO dbo.AuditLog (CompanyId, UserId, UserName, IPAddress, Module, Action, EntityId, DataBefore, DataAfter)
        VALUES (@P_COMPANY_ID, @P_USER_ID, @P_USER_NAME, @P_IP_ADDRESS, @P_MODULE, @P_ACTION, @P_ENTITY_ID, @P_DATA_BEFORE, @P_DATA_AFTER);

        SET @OUT_RESULT = 'OK';
    END TRY
    BEGIN CATCH
        SET @OUT_RESULT = ERROR_MESSAGE();
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE dbo.SP_AUDIT_LOG_GET_BY_COMPANY
    @P_COMPANY_ID INT,
    @P_MODULE NVARCHAR(50) = NULL,
    @P_USER_ID INT = NULL,
    @P_START_DATE DATETIME2 = NULL,
    @P_END_DATE DATETIME2 = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP 500
           AuditLogId AS AUDIT_LOG_ID, CompanyId AS COMPANY_ID, UserId AS USER_ID, UserName AS USER_NAME,
           IPAddress AS IP_ADDRESS, Module AS MODULE, Action AS ACTION, EntityId AS ENTITY_ID,
           DataBefore AS DATA_BEFORE, DataAfter AS DATA_AFTER, CreatedDate AS CREATED_DATE
    FROM dbo.AuditLog
    WHERE CompanyId = @P_COMPANY_ID
      AND (@P_MODULE IS NULL OR Module = @P_MODULE)
      AND (@P_USER_ID IS NULL OR UserId = @P_USER_ID)
      AND (@P_START_DATE IS NULL OR CreatedDate >= @P_START_DATE)
      AND (@P_END_DATE IS NULL OR CreatedDate <= @P_END_DATE)
    ORDER BY CreatedDate DESC;
END
GO
