CREATE OR ALTER PROCEDURE dbo.SP_ACTIVITY_CATEGORY_GET_BY_COMPANY
    @P_COMPANY_ID INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ActivityCategoryId AS ACTIVITY_CATEGORY_ID, CompanyId AS COMPANY_ID, Name AS NAME,
           IsActive AS IS_ACTIVE, CreatedBy AS CREATED_BY, CreatedDate AS CREATED_DATE,
           ModifiedBy AS MODIFIED_BY, ModifiedDate AS MODIFIED_DATE
    FROM dbo.ActivityCategory
    WHERE CompanyId = @P_COMPANY_ID AND IsDeleted = 0 AND IsActive = 1
    ORDER BY Name;
END
GO

CREATE OR ALTER PROCEDURE dbo.SP_ACTIVITY_CATEGORY_INSERT
    @P_COMPANY_ID INT,
    @P_NAME NVARCHAR(100),
    @P_CREATED_BY INT,
    @P_NEW_ACTIVITY_CATEGORY_ID INT OUTPUT,
    @OUT_RESULT NVARCHAR(400) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        INSERT INTO dbo.ActivityCategory (CompanyId, Name, CreatedBy)
        VALUES (@P_COMPANY_ID, @P_NAME, @P_CREATED_BY);

        SET @P_NEW_ACTIVITY_CATEGORY_ID = CAST(SCOPE_IDENTITY() AS INT);
        SET @OUT_RESULT = 'OK';
    END TRY
    BEGIN CATCH
        SET @OUT_RESULT = ERROR_MESSAGE();
    END CATCH
END
GO
